id_name:
  0: node0
  1: node1
  2: node2
  3: node3
id_ip:
  0: 192.168.5.10
  1: 192.168.5.11
  2: 192.168.5.12
  3: 192.168.5.13
id_p2p_port:
  0: 9000
  1: 9000
  2: 9000
  3: 9000
log_level: 1
max_pool: 10
timeout: 1000
mock_latency: 10
ddos: true
max_payload_size: 500
tx_size: 512
wait_time: 10